### ISSUE TITLE
[SCRUM] 20240725 데일리 스크림 및 회고

### ISSUE THREAD

**Issue by Naknakk** [DeveloperAcademy-POSTECH/2024-MC3-M6-LavenderPhanHani#18]
# 이름
## ❤️‍🔥 오늘 한 일

- 한일
- 한일
- 한일

##  🔖 내일 할 일

- 할 일
- 할 일
- 할 일

## ✍️ 오늘의 회고
```
회고회고회고회고고고 위아래 땡땡떙 지우면 안됩니다
```

**Comment by interstellaar** [comment]
# 호세
## ❤️‍🔥 오늘 한 일

- FB로그인 정상화
- 엉망진창 회원가입 뷰만들기
- 치킨먹기


##  🔖 내일 할 일

- 파이어스토어에 가입정보 저장
- 인앱푸시 구현시작
- 뷰 인간이 쓸순있게 다듬기

## ✍️ 오늘의 회고
```
뷰과 깃은 친해지기 어렵다
```

**Comment by Bright-jeans** [comment]
> # 레오
> ## ❤️‍🔥 오늘 한 일
> * 일러스트 요소 제안 (미니멀리즘 구성으로 전부 사라짐)
> * 온보딩 뷰 짜기(Github-Pull Request)
> 
> ## 🔖 내일 할 일
> * 디자인 컨셉 바닥부터 쏴라라라락
> * 톤 앤 무드
> * 디자인 시스템 및 기존 작업물 정리 합시다ㅏㅏ
> 
> ## ✍️ 오늘의 회고
> ```
> 디자인... 긴밀한 협업... 화이팅!!!
> ```

![image](https://github.com/user-attachments/assets/bc5e5190-758a-4280-86ce-c6381e001112)

**Comment by JungHash** [comment]
# 해시
## ❤️‍🔥 오늘 한 일

- 쿨쿨 자기!
- 배드민턴!
- 죄송합니다!


##  🔖 내일 할 일

- 디자인 시스템 제발 빨리 넘겨주기
- 일러스트 박박 그려서 보여주기
- 타이머 다음 페이지 완성하기

## ✍️ 오늘의 회고
```
일정 관리를 못했음.. 죄송합니다!!! 그리고 체리가 잠을 자게 한다는 것을 알게 되었습니다..
```

**Comment by Lavender-SH** [comment]
# 이름
## ❤️‍🔥 오늘 한 일

- 타이머 현재 시간구현
- 초단위로 줄어들기 구현
- 다이얼 기능 수정
- 취소버튼 구현


##  🔖 내일 할 일

- 타이머 완성하기
- 프로그레스바 완성하기

## ✍️ 오늘의 회고
```
회고회고회고회고고고 위아래 땡땡떙 지우면 안됩니다
```

**Comment by Naknakk** [comment]
# 나기
## ❤️‍🔥 오늘 한 일

- 잠을 잘 잤습니다
- 타이머 뷰 - 피드뷰 전환 스크롤로 구현

##  🔖 내일 할 일

- 스크롤 전환 기기대응
- 코드 정리
- 피드 디테일 완성
- 피드 작성뷰 시작

## ✍️ 오늘의 회고
```
어느새 잠들어서 새벽에 깨어버렸습니다. . . .
```
