### ISSUE TITLE
[SCRUM] 20240722 데일리 스크림 및 회고

### ISSUE THREAD

**Issue by Naknakk** [DeveloperAcademy-POSTECH/2024-MC3-M6-LavenderPhanHani#2]
# 이름
## ❤️‍🔥 오늘 한 일

- 한일
- 한일
- 한일

##  🔖 내일 할 일

- 할 일
- 할 일
- 할 일

## ✍️ 오늘의 회고
```
회고회고회고회고고고 위아래 땡땡떙 지우면 안됩니다
```

**Comment by JungHash** [comment]
# 정해시
## ❤️‍🔥 오늘 한 일

- 아이스크림 맛있게 먹기
- 레퍼런스 찾기
- 디자인ing....(식곤증 이슈로 2시간 자버림 으악!)


##  🔖 내일 할 일

- 롤케이크 먹기
- 디자인 Keep going
- 디자인 피드백 받기

## ✍️ 오늘의 회고
```
나기가 멋진 깃허브를 만들어줬어요 감사~! 더 열심히 하겠습니드악!!
```

**Comment by interstellaar** [comment]
# 안제호
## ❤️‍🔥 오늘 한 일

- 알고리즘 스터디
- 나기가 보내준 문서 읽어보기
- 두번째 문서는 취침에 드는 푸시를 보낼때 수면인-FB-기상인 과정에서 FB에서 기상인에게 보내기 위해 쓸 가치가 있어보임 (링크 :  https://firebase.google.com/docs/cloud-messaging/ios/device-group?hl=ko&_gl=1*17y43d2*_up*MQ..*_ga*ODE4NTMyNjY2LjE3MjE2NTI5NDk.*_ga_CW55HF8NVT*MTcyMTY1Mjk0OS4xLjAuMTcyMTY1Mjk0OS4wLjAuMA.. )


##  🔖 내일 할 일

- xcode로 진짜 기능 구현 하기
- Searching,써칭,조사,탐구...

## ✍️ 오늘의 회고
```
오후 세션은 뒷 시간이 너무 짧네요, 한게 거의없는데 정신 차리니 12시....
```

**Comment by Naknakk** [comment]
# 나기
## ❤️‍🔥 오늘 한 일

- Firebase 활용 사진 업로드-다운로드 기능 레퍼런스 조사
    - Firestore + Storage 로 firestore에 저장된 사용자 정보에 storage 에 저장한 이미지 url을 넣으면 될 듯
    - 이미지는 jpeg로 저장해야 용량 확보 가능


##  🔖 내일 할 일

- 실제로 프로젝트 만들어서 구현하기
- 현재 목표 Task 확인, 마감 기한 설정하기

## ✍️ 오늘의 회고
```
오후 세션 진짜 뒷 시간이 짧네요. 하루가 금방 끝났습니다..
구현가능한지 알기 위해 레퍼런스를 열심히 찾았는데, 될 것 같습니다! 
실제로 xcode로 내일 진행하면서 테스트해볼게요.

잘 끝난다면 이후로는 카메라 커스텀 부분을 파고들어야겠네요..
조금 늦게 자게 되었는데, 컨디션 괜찮기를 기도합니다 
```

**Comment by Bright-jeans** [comment]
> # Co-레오
> ## ❤️‍🔥 오늘 한 일
> * 낮잠(약먹고 푹잠)
> * 피드 디자인(진입방법, 주요기능, Lo-fi)
> 
> ## 🔖 내일 할 일
> * 피드 부분에서 와이어프레임 정하기(w/정해시)
> * 레퍼런스 공유(w/정해시)
> * 친구추가 디자인
> * 낮잠 개운함 평가방법 추가고민
> 
> ## ✍️ 오늘의 회고
> ```
> 잠온다... 약 먹으니까 하루종일 꾸벅꾸벅쓰... 
> 여러분 코로나 조심하세여어
> ```

**Comment by Lavender-SH** [comment]
# 이승현
## ❤️‍🔥 오늘 한 일

* 깃 공부 (cherry-pick, fast-forward, squash, rebase merge) + 명령어
* 타이머 라이브러리 찾아보기

##  🔖 내일 할 일

- * 타이머 구현방법

## ✍️ 오늘의 회고
```
회고회고회고회고고고 위아래 땡땡떙 지우면 안됩니다
```
